name: Setup Tauri Dependencies
description: Install system dependencies required for Tauri builds
runs:
  using: composite
  steps:
    - name: Install Tauri dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          patchelf
